#:schema node_modules/wrangler/config-schema.json
name = "ts-web-base-stack"

main = "./build/server/index.js"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "pnpm run build"